run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - errcheck
    - revive

# Disable schema validation in VS Code
# yaml-language-server: $schema=