run:
  timeout: 5m
  tests: true
  go: '1.24'

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - errcheck
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0